# -*- coding: utf-8 -*-
"""
Created on Thu May 13 22:50:55 2021

@author: max
"""

controls.append(epidemic_control(0,"Distancing & Facemasks","Although this is the most basic measure, it is one of the most effective\n at inhibiting the spread of disease. However, it may affect people's mental wellbeing as you're unable\n to hug your loved ones and it may affect the economy as shops and restaurants are unlikely to do as well\n if fewer people are allowed in them as they must be spread further apart.\n ",DISTANCING,[0.6,0.7,0.9,0.9,0.8,0.6], 3.9))
controls.append(epidemic_control(1,"Early Closing","This will significantly affect the economy as there won't be as much revenue coming\n in to the pubs. Also, the average British person won't be too happy about this.\n\n\n" ,PUBS,[1.7,1.7,1.7,1.7,1.7,1.7], 1.9))
controls.append(epidemic_control(2,"Close Non-essential Shops","Shops play a huge role in the country's economy - if they were to close,\n many people would lose their jobs and have to go on furlough, and the government would suffer, as\n would the mental wellbeing of the people who no longer have a day job, and some independent shops may have\n to close permanently due to the lack of income. However, indoor spaces are a breeding ground for\n viruses like Covid-19. ",NON_ESSENTIAL,[0.7,0.7,0.9,0.9,0.8,0.7], 16))
controls.append(epidemic_control(3,"Close International Borders","Although closing the borders will make it much harder for Covid-19 and\n its new variants to spread to the UK, it will have a huge impact on the airline industry. It also\n stops family and friends who live abroad from seeing each other which will affect their wellbeing, as well\n as stop people from taking nice mental breaks to go on holiday.\n",BORDERS,[0.7,0.7,0.7,0.7,0.7,0.7], 64))
controls.append(epidemic_control(4,"Total Lockdown","A full scale lockdown is the best measure to control the spread of the virus, but would\n have devastating effects both socially and econmically: children won't get their necessary\n social interactions and their learning will be affected, people won't get to see their family and friends,\n which is an integral part of human nature, and won't be able to go to work; many people would have\n to work from home or go on furlough, and the government, as well as business owners for example would struggle financially, just to name a few. ",LOCKDOWN,[0.4,0.4,0.7,0.8,0.6,0.3], 146))




periods.append(period(0, 3.2,"Period 1 - January and February","The Health Secretary has informed you that the initial R-Rate is 3.2\n\n Of course, it is very cold throughout January and February and people are naturally coming down\n with the flu over winter. As a rule, spending is low across the UK in retail, but the public still desire\n eating out and drinking in cosy pubs. Although, it is proven that keeping pubs open has a direct\n correlation against the spread of virus. The health secretary advises against keeping cosy pubs open.\n\n"))
periods.append(period(1, 2.7,"Period 2 - March and April","The Health Secretary has informed you that the new R-Rate is 2.7\n\nThere are tens of thousands of young people currently travelling around South East Asia in hope to\n ‘find themselves’, where there is another variant of a similar virus here in the UK spreading\n simultaneously. A national lockdown has been advised as the spread of the virus has gone\n worldwide, although this is due to have severe economic downfall, and also cause a mental health crisis.\n\n"))
periods.append(period(2, 2.1,"Period 3 - May and June","The Health Secretary has informed you that the new R-Rate is 2.1\n\nAs the summer months are closely approaching, temperatures are rising to a point\n where the virus is less transmittable. Many students and young people have upcoming\n exams, which they are severely stressed about. Not only have they left\n revision to last minute, but they are also uncertain on whether exams will be happening at all.\n\n"))
periods.append(period(3, 1.5,"Period 4 - July and August","The Health Secretary has informed you that the new R-Rate is 1.5\n\n Summer is among us. The public are craving a more relaxed set of restrictions\n as the vast majority of the population have felt very isolated and nervous\n this year, due to the level of uncertainty brought by the virus. Everyone is\n craving a holiday overseas to relax and unwind as sadly British weather doesn't always cooperate.\n\n"))
periods.append(period(4, 2.0,"Period 5 - September and October","The Health Secretary has informed you that the new R-Rate is 2.0\n\n As summer closes to an end, the new academic year is looming over us. Students\n and staff seek security and certainty for the forthcoming months, as the previous academic\n year had been meddled with by the scare and anxiety of the virus, and different parameters\n put into place in a bid to reduce the R-rate.\n\n"))
periods.append(period(5, 2.9,"Period 6 - November and December","The Health Secretary has informed you that the new R-Rate is 2.9\n\n As we edge into Winter, a sharp bite in dropping temperatures swarm the UK, giving the virus\n a stronger environment to spread and mutate in. Arriving close to December, retail and hospitality\n face the busiest periods of the year, in hope of capitalising on what has been a terrible year\n otherwise. \n\n"))
